import React, { createContext, useContext, useState, useEffect } from 'react';

const GlobalContext = createContext();

export const useGlobal = () => useContext(GlobalContext);

export const GlobalProvider = ({ children }) => {
    // Theme State
    const [theme, setTheme] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('theme') || 'light';
        }
        return 'light';
    });

    // Language State
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') return localStorage.getItem('language') || 'es';
        return 'es';
    });

    // Apply Theme Side Effect
    useEffect(() => {
        const root = window.document.documentElement;
        if (theme === 'dark') {
            root.classList.add('dark');
        } else {
            root.classList.remove('dark');
        }
        localStorage.setItem('theme', theme);
    }, [theme]);

    // Apply Language Side Effect
    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    // Simple Translation Helper
    const t = (key) => {
        const translations = {
            es: {
                // Sidebar
                'sidebar.rebalance': 'Rebalanceador',
                'sidebar.performance': 'Rentabilidad',
                'sidebar.xray': 'Radiografía',
                'sidebar.analysis': 'Análisis',
                'sidebar.simulations': 'Simulaciones',
                'sidebar.news': 'Noticias',
                'sidebar.settings': 'Ajustes',
                'header.xray': 'Radiografía de Cartera',
                // X-ray
                'xray.whole': 'Toda la cartera',
                'xray.companies': 'Empresas (look-through)',
                'xray.countries': 'Países / Regiones',
                'xray.currencies': 'Divisas',
                'xray.sectors': 'Sectores',
                'xray.search': 'Busca una empresa (ej. NVIDIA, Toyota)…',
                'xray.no_data': 'Añade activos para radiografiar tu cartera.',
                'xray.holdings': 'Posiciones reales',
                'xray.top_country': 'Mayor país/región',
                'xray.top_sector': 'Mayor sector',
                'xray.exposure': 'Exposición total',
                'xray.direct': 'Directo',
                'xray.no_match': 'Ninguna empresa coincide con la búsqueda.',
                'xray.select_portfolio': 'Selecciona una cartera para radiografiarla.',
                'sidebar.new_portfolio': 'Nueva Cartera',
                'sidebar.my_portfolios': 'Mis Carteras',
                'sidebar.logout': 'Cerrar Sesión',
                'portfolio.rename': 'Renombrar',
                'portfolio.duplicate': 'Duplicar',
                'portfolio.delete': 'Eliminar',
                'header.rebalancer': 'Rebalanceador',
                'header.performance': 'Rentabilidad',
                'header.analysis': 'Análisis de Activos',
                'header.simulations': 'Proyecciones Financieras',
                'header.news': 'Noticias del Mercado',
                'header.settings': 'Ajustes de Cuenta',
                'header.user': 'Usuario',
                // News
                'news.sentiment': 'Sentimiento Global (RSI)',
                'news.score': 'Puntuación global',
                'news.analyzed': 'Noticias analizadas',
                'news.none': 'No hay noticias recientes para tus activos.',
                'news.rsi': 'Indicador RSI',
                'news.read': 'Leer artículo',
                'news.select_portfolio': 'Selecciona una cartera para ver sus noticias.',
                // Simulations
                'sim.select_portfolio': '1. Selecciona cartera',
                'sim.model': '2. Modelo de proyección',
                'sim.params': '3. Parámetros',
                'sim.horizon': 'Horizonte',
                'sim.years': 'Años',
                'sim.monthly': 'Aportación mensual',
                'sim.growing': 'Aportación creciente (IPC)',
                'sim.annual_growth': 'Crecimiento anual (%)',
                'sim.apply_tax': 'Aplicar impuestos (19%)',
                'sim.linear': 'Lineal (7%)',
                'sim.linear_desc': 'Proyección constante estándar.',
                'sim.montecarlo': 'Monte Carlo',
                'sim.montecarlo_desc': 'Simula la volatilidad real del mercado.',
                'sim.conservative': 'Conservador (4%)',
                'sim.conservative_desc': 'Escenario de bajo rendimiento.',
                'sim.empty': 'Configura y simula',
                'sim.profit': 'Beneficio',
                'sim.loss': 'Pérdida',
                'sim.select_alert': 'Selecciona al menos una cartera',
                'sim.error': 'Error al ejecutar la simulación.',
                // Dashboard / KPIs
                'kpi.total_value': 'Valor Total',
                'kpi.current_capital': 'Capital Actual',
                'kpi.risk': 'Perfil de Riesgo',
                'kpi.aggressive': 'Agresivo',
                'kpi.moderate': 'Moderado',
                'kpi.conservative': 'Conservador',
                'kpi.contribution': 'Aportación Mensual',
                'kpi.composition': 'Composición',
                'kpi.no_assets': 'Sin activos',
                'dash.search': 'Buscar (ej. Apple, BTC)...',
                'dash.distribution': 'Distribución',
                'dash.plan_title': 'Plan de Rebalanceo',
                'dash.mode_contribute': 'Solo aportar',
                'dash.mode_full': 'Rebalanceo total',
                'dash.mode_contribute_hint': 'Reparte tu aportación mensual sin vender nada.',
                'dash.mode_full_hint': 'Compra y vende para clavar tus objetivos.',
                'dash.apply_contribute': 'Registrar Aportación',
                'dash.apply_full': 'Aplicar Rebalanceo',
                'dash.target_sum': 'Suma objetivos',
                'dash.balanced': 'equilibrado',
                'dash.fix_settings': 'Ajústalos en Ajustes',
                'dash.empty': 'Añade activos para generar tu plan',
                'dash.history': 'Historial de Operaciones',
                'dash.contribution_short': 'Aportación',
                'dash.to_invest_summary': 'A invertir este mes',
                'dash.unallocated': 'Sin asignar',
                // Table headers
                'th.asset': 'Activo',
                'th.price': 'Precio',
                'th.units': 'Uds',
                'th.value': 'Valor',
                'th.now': 'Actual',
                'th.target': 'Objetivo',
                'th.invest': 'A invertir',
                'th.totals': 'Totales',
                'act.buy': 'Comprar',
                'act.sell': 'Vender',
                'act.hold': 'Mantener',
                // Targets (Settings)
                'targets.title': 'Asignación Objetivo',
                'targets.equal': 'Repartir igual',
                'targets.normalize': 'Ajustar a 100%',
                'targets.sum': 'Suma',
                'targets.balanced': 'Equilibrada (100%)',
                'targets.no_portfolio': 'Selecciona o crea una cartera para fijar sus objetivos.',
                'targets.no_assets': 'Esta cartera aún no tiene activos. Añádelos desde el Rebalanceador.',
                'targets.hint': 'La suma debe ser 100%. También puedes editarlos en la tabla del Rebalanceador.',
                'targets.import': 'Importar posiciones (CSV)',
                // Performance / Rentabilidad
                'perf.title': 'Rentabilidad',
                'perf.since': 'Desde',
                'perf.portfolio_value': 'Valor del portafolio',
                'perf.invested': 'Invertido',
                'perf.cashflow': 'Flujo de caja',
                'perf.gain': 'Ganancia',
                'perf.tir': 'TIR (anual)',
                'perf.tir_hint': 'Tasa interna de retorno, ponderada por dinero y tiempo.',
                'perf.simple_return': 'Rentabilidad total',
                'perf.net_total': 'Total neto',
                'perf.fees': 'Comisiones',
                'perf.taxes': 'Impuestos',
                'perf.evolution': 'Evolución del valor',
                'perf.no_data': 'Importa tu CSV de Trade Republic para ver todas las estadísticas de tu cartera.',
                'perf.net_hint': 'Introduce comisiones e impuestos para obtener tu total neto (opcional).',
                'perf.select_portfolio': 'Selecciona una cartera para ver su rentabilidad.',
                'perf.ttwror': 'TTWROR',
                'perf.ttwror_hint': 'Rentabilidad ponderada por tiempo (time-weighted rate of return).',
                'perf.price_gains': 'Ganancias de precio',
                'perf.realized': 'Realizado (Bruto)',
                'perf.dividends': 'Dividendos (Brutos)',
                'perf.interest': 'Intereses (Brutos)',
                'perf.total_gross': 'Total',
                'perf.cost_basis': 'Base de coste',
                'perf.period_since': 'Desde',
                // Trade Republic CSV import
                'tr.drop': 'Arrastra aquí tu CSV de Trade Republic',
                'tr.hint': 'o toca para elegir el archivo · se procesa en tu dispositivo, no se sube a ningún sitio',
                'tr.parsing': 'Procesando tus movimientos…',
                'tr.clear': 'Quitar',
                'tr.err_type': 'El archivo debe ser un .csv',
                'tr.err_empty': 'No se han encontrado movimientos en el archivo.',
                'tr.err_parse': 'Error procesando el CSV. Asegúrate de que es el export de Trade Republic.',
                'tr.since_first': 'Desde tu primera compra',
                'tr.title': 'Importar historial (Trade Republic)',
                'tr.update': 'Actualizar',
                'tr.imported_title': 'Datos importados',
                'tr.imported_hint': 'Tu historial de Trade Republic está cargado.',
                'tr.onboarding_title': 'Conecta tu historial de Trade Republic',
                'tr.onboarding_desc': 'Importa tu CSV de transacciones para ver todas las estadísticas detalladas: rentabilidad, dividendos, comisiones y más.',
                'tr.step1_title': 'Exporta tu CSV',
                'tr.step1_desc': 'En Trade Republic → Actividad → Exportar transacciones.',
                'tr.step2_title': 'Arrástralo aquí',
                'tr.step2_desc': 'Se procesa 100% en tu dispositivo. No se sube a ningún servidor.',
                // Benchmark
                'bench.title': 'Comparativa con índices',
                'bench.hint': 'Tu cartera actual frente a los principales índices (base 100).',
                'bench.asset': 'Cartera / Índice',
                'bench.return': 'Retorno',
                'bench.cagr': 'CAGR anual.',
                'bench.vol': 'Volatilidad',
                'bench.maxdd': 'Máx. caída',
                'bench.beta': 'Beta',
                'bench.corr': 'Correl.',
                'bench.your_portfolio': 'Tu cartera',
                'bench.no_data': 'No hay datos suficientes para comparar.',
                'bench.select_hint': 'Elige uno o más índices para comparar.',
                // Cost basis / profit since purchase
                'cost.title': 'Historial de compras (coste)',
                'cost.hint': 'Pega tus compras (símbolo, fecha AAAA-MM-DD, unidades, precio) o edita el precio medio por activo. Se calcula tu beneficio desde que compraste. Se guarda solo en este dispositivo.',
                'cost.placeholder': 'AAPL, 2025-11-24, 3, 180\nBTC-EUR, 2025-12-01, 0.05, 55000\n...',
                'cost.apply': 'Calcular beneficio',
                'cost.profit_title': 'Beneficio desde la compra',
                'cost.asset': 'Activo',
                'cost.avg_cost': 'Coste medio',
                'cost.invested': 'Invertido',
                'cost.value': 'Valor actual',
                'cost.profit': 'Beneficio',
                'cost.since': 'Desde',
                'cost.total': 'Total',
                'cost.none': 'Aún no has definido compras. Pega tu historial arriba para ver tu beneficio por activo.',
                'cost.total_profit': 'Beneficio total (desde compra)',
                // CSV import
                'csv.title': 'Sincronizar posiciones',
                'csv.hint': 'Pega un CSV (símbolo/ISIN/nombre, unidades) de Trade Republic o Parqet para actualizar tus unidades. Como Fandance usa precios de mercado en vivo, si las unidades coinciden el valor será idéntico al de tu bróker.',
                'csv.placeholder': 'AAPL, 3.5\nVWCE, 12\n...',
                'csv.apply': 'Actualizar unidades',
                'csv.matched': 'actualizados',
                'csv.unmatched': 'sin coincidencia',
                // Analysis
                'analysis.title': 'Análisis de Activos',
                'analysis.loading': 'Cargando datos...',
                'analysis.no_data': 'No hay datos disponibles.',
                // Settings
                'settings.appearance': 'Apariencia',
                'settings.theme': 'Tema Visual',
                'settings.dark': 'Oscuro',
                'settings.light': 'Claro',
                'settings.language': 'Idioma',
                'settings.account': 'Cuenta',
                'settings.logout': 'Cerrar Sesión',
                'settings.about': 'Información',
                // Simulations
                'sim.title': 'Proyecciones',
                'sim.calculate': 'Calcular Proyección',
                'sim.investment': 'Inversión Total',
                'sim.gross': 'Valor Bruto',
                'sim.net': 'Neto tras Impuestos',
                // Bottom Nav (mobile)
                'nav.rebalance': 'Cartera',
                'nav.xray': 'X-Ray',
                'nav.analysis': 'Análisis',
                'nav.news': 'Noticias',
                'nav.more': 'Más',
                'nav.performance': 'Rentabilidad',
                'nav.simulations': 'Simulaciones',
                'nav.settings': 'Ajustes',
                'nav.logout': 'Cerrar Sesión',
                'nav.portfolio': 'Cartera activa',
                // X-Ray regions
                'xray.regions': 'Regiones',
                'xray.showing': 'Mostrando',
                'xray.of': 'de',
                'xray.load_more': 'Cargar más',
                // Dashboard allocation
                'dash.allocation': 'Asignación actual'
            },
            en: {
                // Sidebar
                'sidebar.rebalance': 'Rebalancer',
                'sidebar.performance': 'Performance',
                'sidebar.xray': 'X-Ray',
                'sidebar.analysis': 'Analysis',
                'sidebar.simulations': 'Simulations',
                'sidebar.news': 'News',
                'sidebar.settings': 'Settings',
                'header.xray': 'Portfolio X-Ray',
                // X-ray
                'xray.whole': 'Whole portfolio',
                'xray.companies': 'Companies (look-through)',
                'xray.countries': 'Countries / Regions',
                'xray.currencies': 'Currencies',
                'xray.sectors': 'Sectors',
                'xray.search': 'Find a company (e.g. NVIDIA, Toyota)…',
                'xray.no_data': 'Add assets to X-ray your portfolio.',
                'xray.holdings': 'Real holdings',
                'xray.top_country': 'Top country/region',
                'xray.top_sector': 'Top sector',
                'xray.exposure': 'Total exposure',
                'xray.direct': 'Direct',
                'xray.no_match': 'No company matches your search.',
                'xray.select_portfolio': 'Select a portfolio to X-ray it.',
                'sidebar.new_portfolio': 'New Portfolio',
                'sidebar.my_portfolios': 'My Portfolios',
                'sidebar.logout': 'Log Out',
                'portfolio.rename': 'Rename',
                'portfolio.duplicate': 'Duplicate',
                'portfolio.delete': 'Delete',
                'header.rebalancer': 'Rebalancer',
                'header.performance': 'Performance',
                'header.analysis': 'Asset Analysis',
                'header.simulations': 'Financial Projections',
                'header.news': 'Market News',
                'header.settings': 'Account Settings',
                'header.user': 'User',
                // News
                'news.sentiment': 'Global Portfolio Sentiment (RSI)',
                'news.score': 'Global Score',
                'news.analyzed': 'Analyzed News',
                'news.none': 'No recent news for your assets.',
                'news.rsi': 'RSI Indicator',
                'news.read': 'Read Article',
                'news.select_portfolio': 'Select a portfolio to see its news.',
                // Simulations
                'sim.select_portfolio': '1. Select portfolio',
                'sim.model': '2. Projection Model',
                'sim.params': '3. Parameters',
                'sim.horizon': 'Horizon',
                'sim.years': 'Years',
                'sim.monthly': 'Monthly Contribution',
                'sim.growing': 'Growing Contribution (CPI)',
                'sim.annual_growth': 'Annual Growth (%)',
                'sim.apply_tax': 'Apply Tax (19%)',
                'sim.linear': 'Linear (7%)',
                'sim.linear_desc': 'Standard constant projection.',
                'sim.montecarlo': 'Monte Carlo',
                'sim.montecarlo_desc': 'Simulates real market volatility.',
                'sim.conservative': 'Conservative (4%)',
                'sim.conservative_desc': 'Low performance scenario.',
                'sim.empty': 'Configure and simulate',
                'sim.profit': 'Profit',
                'sim.loss': 'Loss',
                'sim.select_alert': 'Select at least one portfolio',
                'sim.error': 'Error running simulation.',
                // Dashboard / KPIs
                'kpi.total_value': 'Total Value',
                'kpi.current_capital': 'Current Capital',
                'kpi.risk': 'Risk Profile',
                'kpi.aggressive': 'Aggressive',
                'kpi.moderate': 'Moderate',
                'kpi.conservative': 'Conservative',
                'kpi.contribution': 'Monthly Contribution',
                'kpi.composition': 'Composition',
                'kpi.no_assets': 'No assets',
                'dash.search': 'Search (e.g. Apple, BTC)...',
                'dash.distribution': 'Distribution',
                'dash.plan_title': 'Rebalancing Plan',
                'dash.mode_contribute': 'Contribute only',
                'dash.mode_full': 'Full rebalance',
                'dash.mode_contribute_hint': 'Spread your monthly money, no selling.',
                'dash.mode_full_hint': 'Buy & sell to hit your targets exactly.',
                'dash.apply_contribute': 'Log Contribution',
                'dash.apply_full': 'Apply Rebalance',
                'dash.target_sum': 'Target sum',
                'dash.balanced': 'balanced',
                'dash.fix_settings': 'Set them in Settings',
                'dash.empty': 'Add assets to build your plan',
                'dash.history': 'Operations History',
                'dash.contribution_short': 'Contribution',
                'dash.to_invest_summary': 'To invest this month',
                'dash.unallocated': 'Unallocated',
                // Table headers
                'th.asset': 'Asset',
                'th.price': 'Price',
                'th.units': 'Units',
                'th.value': 'Value',
                'th.now': 'Now',
                'th.target': 'Target',
                'th.invest': 'To invest',
                'th.totals': 'Totals',
                'act.buy': 'Buy',
                'act.sell': 'Sell',
                'act.hold': 'Hold',
                // Targets (Settings)
                'targets.title': 'Target Allocation',
                'targets.equal': 'Equal split',
                'targets.normalize': 'Scale to 100%',
                'targets.sum': 'Sum',
                'targets.balanced': 'Balanced (100%)',
                'targets.no_portfolio': 'Select or create a portfolio to set its targets.',
                'targets.no_assets': 'This portfolio has no assets yet. Add them from the Rebalancer.',
                'targets.hint': 'The sum should be 100%. You can also edit them in the Rebalancer table.',
                'targets.import': 'Import holdings (CSV)',
                // Performance
                'perf.title': 'Performance',
                'perf.since': 'Since',
                'perf.portfolio_value': 'Portfolio value',
                'perf.invested': 'Invested',
                'perf.cashflow': 'Cash flow',
                'perf.gain': 'Gain',
                'perf.tir': 'IRR (annual)',
                'perf.tir_hint': 'Internal rate of return, weighted by money and time.',
                'perf.simple_return': 'Total return',
                'perf.net_total': 'Net total',
                'perf.fees': 'Fees',
                'perf.taxes': 'Taxes',
                'perf.evolution': 'Value evolution',
                'perf.no_data': 'Import your Trade Republic CSV to see all portfolio stats.',
                'perf.net_hint': 'Enter fees and taxes to get your net total (optional).',
                'perf.select_portfolio': 'Select a portfolio to see its performance.',
                'perf.ttwror': 'TTWROR',
                'perf.ttwror_hint': 'Time-weighted rate of return.',
                'perf.price_gains': 'Price gains',
                'perf.realized': 'Realized (Gross)',
                'perf.dividends': 'Dividends (Gross)',
                'perf.interest': 'Interest (Gross)',
                'perf.total_gross': 'Total',
                'perf.cost_basis': 'Cost basis',
                'perf.period_since': 'Since',
                // Trade Republic CSV import
                'tr.drop': 'Drop your Trade Republic CSV here',
                'tr.hint': 'or tap to choose the file · parsed on your device, never uploaded',
                'tr.parsing': 'Processing your transactions…',
                'tr.clear': 'Remove',
                'tr.err_type': 'The file must be a .csv',
                'tr.err_empty': 'No transactions found in the file.',
                'tr.err_parse': 'Could not parse the CSV. Make sure it is the Trade Republic export.',
                'tr.since_first': 'Since your first purchase',
                'tr.title': 'Import history (Trade Republic)',
                'tr.update': 'Update',
                'tr.imported_title': 'Data imported',
                'tr.imported_hint': 'Your Trade Republic history is loaded.',
                'tr.onboarding_title': 'Connect your Trade Republic history',
                'tr.onboarding_desc': 'Import your transaction CSV to see full detailed stats: returns, dividends, fees and more.',
                'tr.step1_title': 'Export your CSV',
                'tr.step1_desc': 'In Trade Republic → Activity → Export transactions.',
                'tr.step2_title': 'Drop it here',
                'tr.step2_desc': 'Processed 100% on your device. Never uploaded to any server.',
                // Benchmark
                'bench.title': 'Benchmark comparison',
                'bench.hint': 'Your current holdings vs the major indices (base 100).',
                'bench.asset': 'Portfolio / Index',
                'bench.return': 'Return',
                'bench.cagr': 'CAGR annual.',
                'bench.vol': 'Volatility',
                'bench.maxdd': 'Max drawdown',
                'bench.beta': 'Beta',
                'bench.corr': 'Corr.',
                'bench.your_portfolio': 'Your portfolio',
                'bench.no_data': 'Not enough data to compare.',
                'bench.select_hint': 'Pick one or more indices to compare.',
                // Cost basis / profit since purchase
                'cost.title': 'Purchase history (cost)',
                'cost.hint': 'Paste your buys (symbol, date YYYY-MM-DD, units, price) or edit the average cost per asset. Your profit since purchase is computed. Stored on this device only.',
                'cost.placeholder': 'AAPL, 2025-11-24, 3, 180\nBTC-EUR, 2025-12-01, 0.05, 55000\n...',
                'cost.apply': 'Compute profit',
                'cost.profit_title': 'Profit since purchase',
                'cost.asset': 'Asset',
                'cost.avg_cost': 'Avg cost',
                'cost.invested': 'Invested',
                'cost.value': 'Current value',
                'cost.profit': 'Profit',
                'cost.since': 'Since',
                'cost.total': 'Total',
                'cost.none': 'No purchases defined yet. Paste your history above to see profit per asset.',
                'cost.total_profit': 'Total profit (since purchase)',
                // CSV import
                'csv.title': 'Sync holdings',
                'csv.hint': 'Paste a CSV (symbol/ISIN/name, units) from Trade Republic or Parqet to update your units. Since Fandance uses live market prices, when units match the value is identical to your broker.',
                'csv.placeholder': 'AAPL, 3.5\nVWCE, 12\n...',
                'csv.apply': 'Update units',
                'csv.matched': 'updated',
                'csv.unmatched': 'no match',
                // Analysis
                'analysis.title': 'Asset Analysis',
                'analysis.loading': 'Loading data...',
                'analysis.no_data': 'No data available.',
                // Settings
                'settings.appearance': 'Appearance',
                'settings.theme': 'Visual Theme',
                'settings.dark': 'Dark',
                'settings.light': 'Light',
                'settings.language': 'Language',
                'settings.account': 'Account',
                'settings.logout': 'Log Out',
                'settings.about': 'About',
                // Simulations
                'sim.title': 'Projections',
                'sim.calculate': 'Run Projection',
                'sim.investment': 'Total Invested',
                'sim.gross': 'Gross Value',
                'sim.net': 'Net after Tax',
                // Bottom Nav (mobile)
                'nav.rebalance': 'Portfolio',
                'nav.xray': 'X-Ray',
                'nav.analysis': 'Analysis',
                'nav.news': 'News',
                'nav.more': 'More',
                'nav.performance': 'Performance',
                'nav.simulations': 'Projections',
                'nav.settings': 'Settings',
                'nav.logout': 'Log Out',
                'nav.portfolio': 'Active portfolio',
                // X-Ray regions
                'xray.regions': 'Regions',
                'xray.showing': 'Showing',
                'xray.of': 'of',
                'xray.load_more': 'Load more',
                // Dashboard allocation
                'dash.allocation': 'Current allocation'
            }
        };
        return translations[language][key] || key;
    };

    return (
        <GlobalContext.Provider value={{ theme, setTheme, language, setLanguage, t }}>
            {children}
        </GlobalContext.Provider>
    );
};
