import React, { createContext, useContext, useState, useEffect } from 'react';

const GlobalContext = createContext();

export const useGlobal = () => useContext(GlobalContext);

export const GlobalProvider = ({ children }) => {
    // Theme State
    const [theme, setTheme] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('theme') || 'light';
        }
        return 'light';
    });

    // Language State
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') return localStorage.getItem('language') || 'es';
        return 'es';
    });

    // Apply Theme Side Effect
    useEffect(() => {
        const root = window.document.documentElement;
        if (theme === 'dark') {
            root.classList.add('dark');
        } else {
            root.classList.remove('dark');
        }
        localStorage.setItem('theme', theme);
    }, [theme]);

    // Apply Language Side Effect
    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    // Simple Translation Helper
    const t = (key) => {
        const translations = {
            es: {
                // Sidebar
                'sidebar.rebalance': 'Rebalanceador',
                'sidebar.performance': 'Rentabilidad',
                'sidebar.xray': 'Radiografía',
                'sidebar.analysis': 'Análisis',
                'sidebar.simulations': 'Simulaciones',
                'sidebar.news': 'Noticias',
                'sidebar.settings': 'Ajustes',
                'header.xray': 'Radiografía de Cartera',
                // X-ray
                'xray.whole': 'Toda la cartera',
                'xray.companies': 'Empresas (look-through)',
                'xray.countries': 'Países',
                'xray.currencies': 'Divisas',
                'xray.sectors': 'Sectores',
                'xray.search': 'Busca una empresa (ej. NVIDIA, Toyota)…',
                'xray.no_data': 'Añade activos para radiografiar tu cartera.',
                'xray.holdings': 'Posiciones reales',
                'xray.top_country': 'Mayor país',
                'xray.top_sector': 'Mayor sector',
                'xray.exposure': 'Exposición total',
                'xray.direct': 'Directo',
                'xray.no_match': 'Ninguna empresa coincide con la búsqueda.',
                'xray.select_portfolio': 'Selecciona una cartera para radiografiarla.',
                'sidebar.new_portfolio': 'Nueva Cartera',
                'sidebar.my_portfolios': 'Mis Carteras',
                'sidebar.logout': 'Cerrar Sesión',
                'portfolio.rename': 'Renombrar',
                'portfolio.duplicate': 'Duplicar',
                'portfolio.delete': 'Eliminar',
                'header.rebalancer': 'Rebalanceador',
                'header.performance': 'Rentabilidad',
                'header.analysis': 'Análisis de Activos',
                'header.simulations': 'Proyecciones Financieras',
                'header.news': 'Noticias del Mercado',
                'header.settings': 'Ajustes de Cuenta',
                'header.user': 'Usuario',
                // News
                'news.sentiment': 'Sentimiento Global (RSI)',
                'news.score': 'Puntuación global',
                'news.analyzed': 'Noticias analizadas',
                'news.none': 'No hay noticias recientes para tus activos.',
                'news.rsi': 'Indicador RSI',
                'news.read': 'Leer artículo',
                'news.select_portfolio': 'Selecciona una cartera para ver sus noticias.',
                // Simulations
                'sim.select_portfolio': 'Carteras a proyectar',
                'sim.model': 'Modelo',
                'sim.params': '3. Parámetros',
                'sim.horizon': 'Horizonte',
                'sim.until': "hasta",
                'sim.snap_target': "Ajustar a mi fecha objetivo ({y} años)",
                'sim.years': 'Años',
                'sim.monthly': 'Aporte mensual',
                'sim.growing': 'Aportación creciente (IPC)',
                'sim.annual_growth': 'Subida anual',
                'sim.apply_tax': 'Aplicar impuestos (19%)',
                'sim.linear': 'Lineal',
                'sim.linear_desc': 'Rentabilidad constante del 7% anual.',
                'sim.montecarlo': 'Monte Carlo',
                'sim.montecarlo_desc': 'Simula la volatilidad real del mercado.',
                'sim.conservative': 'Prudente',
                'sim.conservative_desc': 'Escenario de bajo rendimiento: 4% anual.',
                'sim.empty': 'Configura y simula',
                'sim.profit': 'Beneficio',
                'sim.loss': 'Pérdida',
                'sim.select_alert': 'Selecciona al menos una cartera',
                'sim.error': 'Error al ejecutar la simulación.',
                'sim.source': 'Aportaciones',
                'sim.use_plan': 'Mi plan',
                'sim.custom': 'Otros valores',
                'sim.from_plan': 'Se proyecta con tu plan: {m} € al mes, subiendo un {g}% cada año.',
                'sim.no_plan': 'Aún no tienes plan. Fija uno arriba o introduce los valores a mano.',
                // Calendario de aportaciones
                'sched.title': 'Calendario de aportaciones',
                'sched.constant_hint': 'Aportarás la misma cantidad todos los meses del horizonte.',
                'sched.growing_hint': 'Tu aportación sube',
                'sched.per_year': 'al año',
                'sched.per_month': 'al mes',
                'sched.month': 'Mes',
                'sched.year': 'Año',
                'sched.total': 'Total aportado',
                'sched.ends_at': 'Acabarás aportando',
                'sched.empty': 'Introduce una aportación mensual para ver cuánto pondrás cada mes.',
                // Dashboard / KPIs
                'kpi.total_value': 'Valor Total',
                'kpi.current_capital': 'Capital Actual',
                'kpi.risk': 'Perfil de Riesgo',
                'kpi.aggressive': 'Agresivo',
                'kpi.moderate': 'Moderado',
                'kpi.conservative': 'Conservador',
                'kpi.contribution': 'Aportación Mensual',
                'kpi.composition': 'Composición',
                'kpi.per_month': 'al mes',
                'kpi.no_assets': 'Sin activos',
                'dash.search': 'Buscar (ej. Apple, BTC)...',
                'dash.distribution': 'Distribución',
                'dash.plan_title': 'Plan de Rebalanceo',
                'dash.mode_contribute': 'Solo aportar',
                'dash.mode_full': 'Rebalanceo total',
                'dash.mode_contribute_hint': 'Reparte tu aportación mensual sin vender nada.',
                'dash.mode_full_hint': 'Compra y vende para clavar tus objetivos.',
                'dash.apply_contribute': 'Registrar Aportación',
                'dash.apply_full': 'Aplicar Rebalanceo',
                'dash.target_sum': 'Suma objetivos',
                'dash.balanced': 'equilibrado',
                'dash.fix_settings': 'Ajústalos en Ajustes',
                'dash.empty': 'Añade activos para generar tu plan',
                'dash.history': 'Historial de Operaciones',
                'dash.contribution_short': 'Aportación',
                'dash.to_invest_summary': 'A invertir este mes',
                'dash.unallocated': 'Sin asignar',
                'dash.only_this': 'Aportar solo a este activo',
                'dash.manual_amounts': 'Importes fijados a mano',
                'dash.back_to_auto': 'Reparto automático',
                // Table headers
                'th.asset': 'Activo',
                'th.price': 'Precio',
                'th.units': 'Uds',
                'th.value': 'Valor',
                'th.now': 'Actual',
                'th.target': 'Objetivo',
                'th.invest': 'A invertir',
                'th.totals': 'Totales',
                'act.buy': 'Comprar',
                'act.sell': 'Vender',
                'act.hold': 'Mantener',
                // Targets (Settings)
                'targets.title': 'Asignación Objetivo',
                'targets.equal': 'Repartir igual',
                'targets.normalize': 'Ajustar a 100%',
                'targets.sum': 'Suma',
                'targets.balanced': 'Equilibrada (100%)',
                'targets.no_portfolio': 'Selecciona o crea una cartera para fijar sus objetivos.',
                'targets.no_assets': 'Esta cartera aún no tiene activos. Añádelos desde el Rebalanceador.',
                'targets.hint': 'La suma debe ser 100%. También puedes editarlos en la tabla del Rebalanceador.',
                'targets.import': 'Importar posiciones (CSV)',
                // Performance / Rentabilidad
                'perf.title': 'Rentabilidad',
                'perf.since': 'Desde',
                'perf.portfolio_value': 'Valor del portafolio',
                'perf.invested': 'Invertido',
                'perf.cashflow': 'Flujo de caja',
                'perf.gain': 'Ganancia',
                'perf.tir': 'TIR (anual)',
                'perf.tir_hint': 'Tasa interna de retorno, ponderada por dinero y tiempo.',
                'perf.simple_return': 'Rentabilidad total',
                'perf.net_total': 'Total neto',
                'perf.fees': 'Comisiones',
                'perf.taxes': 'Impuestos',
                'perf.evolution': 'Evolución del valor',
                'perf.no_data': 'Importa tu CSV de Trade Republic para ver todas las estadísticas de tu cartera.',
                'perf.net_hint': 'Introduce comisiones e impuestos para obtener tu total neto (opcional).',
                'perf.select_portfolio': 'Selecciona una cartera para ver su rentabilidad.',
                'perf.ttwror': 'TTWROR',
                'perf.ttwror_hint': 'Rentabilidad ponderada por tiempo (time-weighted rate of return).',
                'perf.price_gains_hint': 'La plusvalía latente se mide desde que compraste, no desde el inicio del periodo: no existe precio histórico de tus posiciones para acotarla al periodo.',
                'perf.price_gains': 'Ganancias de precio',
                'perf.realized': 'Realizado (Bruto)',
                'perf.dividends': 'Dividendos (Brutos)',
                'perf.interest': 'Intereses (Brutos)',
                'perf.total_gross': 'Total',
                'perf.cost_basis': 'Base de coste',
                'perf.period_since': 'Desde',
                // Trade Republic CSV import
                'sync.title': "Sincronizar con Trade Republic",
                'sync.stale_price': "Cotizaciones corregidas con el precio de tu bróker",
                'sync.stale_price_hint': "El precio que devuelve el mercado se aleja del último al que ejecutó tu bróker, así que el activo debe de estar dado de alta con otro ticker o en otra divisa. Para que tu patrimonio cuadre se valora con el precio del bróker. Se muestra: precio de la app → precio usado.",
                'pos.precio_csv': "precio del bróker",
                'cargas.title': "Ficheros importados",
                'cargas.hint': "Qué subiste cada día y cuánto movió tu patrimonio invertido.",
                'cargas.empty': "Todavía no has importado ningún fichero",
                'cargas.empty_hint': "Sube el CSV de Trade Republic desde Posiciones y aquí verás cada importación.",
                'cargas.operations': "operaciones",
                'cargas.total': "acumulado",
                'cargas.nothing_new': "sin novedades",
                'cargas.delete': "Borrar este fichero",
                'sync.new_ops': "nuevas",
                'sync.already': "ya estaban",
                'reset.title': "Reiniciar mis datos",
                'reset.hint': "Deja la cuenta a cero conservando tus carteras y tus porcentajes objetivo.",
                'reset.cta': "Reiniciar datos",
                'reset.confirm_title': "Esto no se puede deshacer. Se borrará:",
                'reset.item_history': "el historial de rebalanceos",
                'reset.item_units': "las unidades de cada activo (a cero)",
                'reset.item_plans': "el plan de aportación y los planes guardados",
                'reset.item_csv': "todos los CSV importados",
                'reset.keeps': "Se conservan tus carteras, los activos y los porcentajes objetivo.",
                'reset.confirm_cta': "Sí, reiniciar",
                'reset.done': "Hecho: {h} rebalanceos borrados y {p} posiciones a cero.",
                'reset.error': "No se pudo reiniciar:",
                'aviso.title': "Toca actualizar tu cartera",
                'aviso.pending_one': "Ya se ha ejecutado la aportación de",
                'aviso.pending_many': "Faltan las aportaciones de",
                'aviso.later': "Ahora no",
                'movs.title': "Movimientos",
                'movs.hint': "Todo lo que contiene el CSV importado.",
                'movs.movements': "movimientos",
                'movs.imported': "importado el",
                'movs.clear': "Borrar el CSV guardado",
                'movs.empty': "Aún no has importado ningún CSV",
                'movs.empty_hint': "Sube el export de Trade Republic desde Posiciones y aquí verás todo tu histórico.",
                'movs.f_all': "Todo",
                'movs.f_contrib': "Aportaciones",
                'movs.f_income': "Ingresos",
                'movs.plan': "plan",
                'movs.assets': "activos",
                'movs.more': "Ver meses anteriores",
                'movs.buy': "Compra",
                'movs.sell': "Venta",
                'movs.dividend': "Dividendo",
                'movs.interest': "Intereses",
                'movs.card': "Tarjeta",
                'movs.transfer': "Transferencia",
                'movs.other': "Otro",
                'sync.hint': "Sube el CSV de transacciones y las unidades pasan a ser las que se ejecutaron de verdad. El fichero no sale de tu móvil.",
                'sync.choose': "Elegir CSV",
                'sync.transactions': "movimientos",
                'sync.contributions': "aportaciones",
                'sync.new': "nuevas",
                'sync.dca': "plan",
                'sync.assets': "activos",
                'sync.will_update': "Se actualizarán estas posiciones:",
                'sync.up_to_date': "Tus posiciones ya coinciden con el CSV. No hay nada que aplicar.",
                'sync.unmatched': "Hay activos sin emparejar",
                'sync.only_app': "Solo en la app",
                'sync.only_csv': "Solo en el CSV",
                'sync.apply': "Actualizar posiciones",
                'sync.save_only': "Guardar el histórico",
                'sync.done': "Posiciones actualizadas con las unidades reales.",
                'sync.err_apply': "No se pudieron actualizar las posiciones.",
                'tr.err_empty': 'No se han encontrado movimientos en el archivo.',
                'tr.err_parse': 'Error procesando el CSV. Asegúrate de que es el export de Trade Republic.',
                'tr.since_first': 'Desde tu primera compra',
                'perf.go_import': "Ir a Posiciones para importarlo",
                'tr.update': 'Actualizar',
                'tr.imported_title': 'Datos importados',
                'tr.imported_hint': 'Tu historial de Trade Republic está cargado.',
                'tr.onboarding_title': 'Conecta tu historial de Trade Republic',
                'tr.onboarding_desc': 'Importa tu CSV de transacciones para ver todas las estadísticas detalladas: rentabilidad, dividendos, comisiones y más.',
                // Benchmark
                'bench.title': 'Comparativa con índices',
                'bench.hint': 'Tu cartera actual frente a los principales índices (base 100).',
                'bench.asset': 'Cartera / Índice',
                'bench.return': 'Retorno',
                'bench.cagr': 'CAGR anual.',
                'bench.vol': 'Volatilidad',
                'bench.maxdd': 'Máx. caída',
                'bench.your_portfolio': 'Tu cartera',
                'bench.no_data': 'No hay datos suficientes para comparar.',
                'bench.select_hint': 'Elige uno o más índices para comparar.',
                // Benchmark — métricas relativas (Beta / Correlación)
                'bench.rel_title': 'Análisis frente al mercado',
                'bench.rel_ref': 'Métricas calculadas respecto a',
                'bench.rel_change': 'Cambiar índice de referencia',
                'bench.rel_empty': 'Selecciona un índice arriba para ver tu Beta y Correlación.',
                'bench.rel_insufficient': 'Datos insuficientes',
                'bench.rel_not_computable': 'No calculable',
                'bench.rel_why_insufficient': 'No hay suficiente histórico común entre tu cartera y el índice en este periodo.',
                'bench.rel_why_error': 'El índice no registra variación en este periodo, así que la relación no se puede calcular.',
                'bench.rel_points': 'sesiones comparadas',
                'bench.beta_long': 'Beta',
                'bench.corr_long': 'Correlación',
                'bench.beta_amplify': 'Tu cartera amplifica los movimientos del índice.',
                'bench.beta_inline': 'Tu cartera se mueve casi en línea con el índice.',
                'bench.beta_damp': 'Tu cartera amortigua los movimientos del índice.',
                'bench.beta_inverse': 'Tu cartera es inversamente volátil: se mueve al revés que el índice.',
                'bench.corr_strong': 'Relación muy estrecha con el índice.',
                'bench.corr_moderate': 'Relación moderada con el índice.',
                'bench.corr_weak': 'Apenas guarda relación con el índice.',
                'bench.corr_inverse': 'Correlación inversa: cuando el índice sube, tu cartera tiende a bajar.',
                // Cost basis / profit since purchase
                'cost.title': 'Historial de compras (coste)',
                'cost.hint': 'Pega tus compras (símbolo, fecha AAAA-MM-DD, unidades, precio) o edita el precio medio por activo. Se calcula tu beneficio desde que compraste. Se guarda solo en este dispositivo.',
                'cost.placeholder': 'AAPL, 2025-11-24, 3, 180\nBTC-EUR, 2025-12-01, 0.05, 55000\n...',
                'cost.apply': 'Calcular beneficio',
                'cost.profit_title': 'Beneficio desde la compra',
                'cost.asset': 'Activo',
                'cost.avg_cost': 'Coste medio',
                'cost.invested': 'Invertido',
                'cost.value': 'Valor actual',
                'cost.profit': 'Beneficio',
                'cost.since': 'Desde',
                'cost.total': 'Total',
                'cost.none': 'Aún no has definido compras. Pega tu historial arriba para ver tu beneficio por activo.',
                'cost.total_profit': 'Beneficio total (desde compra)',
                // CSV import
                'csv.title': 'Sincronizar posiciones',
                'csv.hint': 'Pega un CSV (símbolo/ISIN/nombre, unidades) de Trade Republic o Parqet para actualizar tus unidades. Como Fandance usa precios de mercado en vivo, si las unidades coinciden el valor será idéntico al de tu bróker.',
                'csv.placeholder': 'AAPL, 3.5\nVWCE, 12\n...',
                'csv.apply': 'Actualizar unidades',
                'csv.matched': 'actualizados',
                'csv.unmatched': 'sin coincidencia',
                // Analysis
                'analysis.title': 'Análisis de Activos',
                'analysis.loading': 'Cargando datos...',
                'analysis.no_data': 'No hay datos disponibles.',
                'analysis.position_value': 'Valor de tu posición',
                // Settings
                'settings.appearance': 'Apariencia',
                'settings.theme': 'Tema Visual',
                'settings.dark': 'Oscuro',
                'settings.light': 'Claro',
                'settings.language': 'Idioma',
                'settings.account': 'Cuenta',
                'settings.logout': 'Cerrar Sesión',
                'settings.about': 'Información',
                'settings.session': "Sesión actual",
                'about.what': "Fandance reparte tu aportación mensual entre tus fondos indexados para que la cartera vuelva sola a los porcentajes que te fijaste, sin tener que vender.",
                'about.q_rebalance': "¿Cómo se calcula el rebalanceo?",
                'about.a_rebalance': "En «Solo aportar» se reparte tu dinero del mes entre los activos que están más por debajo de su objetivo, así te acercas al plan sin vender nada. En «Rebalanceo total» además se vende para caer justo en el objetivo. Es el enfoque de rebalanceo pasivo que usan los gestores automatizados como Indexa Capital.",
                'about.q_data': "¿Están seguros mis datos?",
                'about.a_data': "Tu cartera se guarda en Supabase, y cada petición comprueba que eres su dueño antes de devolver nada. El CSV de Trade Republic no se sube a ningún servidor: se procesa en el móvil y se borra al cerrar sesión.",
                'about.version': "Versión",
                // Simulations
                'sim.title': 'Proyecciones',
                'sim.calculate': 'Calcular Proyección',
                'sim.investment': 'Inversión Total',
                'sim.gross': 'Valor Bruto',
                'sim.net': 'Neto tras Impuestos',
                // Bottom Nav (mobile)
                'nav.rebalance': 'Cartera',
                'nav.xray': 'X-Ray',
                'nav.analysis': 'Análisis',
                'nav.news': 'Noticias',
                'nav.more': 'Más',
                'nav.performance': 'Rentabilidad',
                'nav.simulations': 'Simulaciones',
                'nav.settings': 'Ajustes',
                'nav.logout': 'Cerrar Sesión',
                'nav.portfolio': 'Cartera activa',
                // X-Ray regions
                'xray.regions': 'Regiones',
                'xray.geo_estimated': 'Los fondos no publican su desglose por país: esa parte se estima con los pesos del índice que replican',
                'xray.showing': 'Mostrando',
                'xray.of': 'de',
                'xray.load_more': 'Ver más',
                'xray.show_all': 'Mostrar todas',
                'xray.collapse': 'Mostrar menos',
                'xray.unclassified': 'sin clasificar',
                'xray.coverage': 'Cobertura del look-through',
                'xray.coverage_note': 'Yahoo Finance sólo publica las 10 mayores posiciones de cada fondo. El resto del peso se reparte proporcionalmente entre ellas, así que el número de empresas es menor que el real.',
                // --- Navegación reorganizada ---
                'nav.home': 'Inicio',
                'nav.positions': 'Posiciones',
                'nav.xray_full': 'Radiografía',
                'nav.history': 'Historial',
                'header.home': 'Inicio',
                'header.positions': 'Posiciones',
                // --- Inicio ---
                'home.net_worth': 'Patrimonio',
                'home.since': 'Desde',
                'home.value': 'Valor',
                'home.no_history': 'Sin histórico todavía',
                'home.act_targets': 'Tus pesos objetivo no suman 100%',
                'home.act_targets_body': 'Ahora mismo suman {sum}%. Hasta que cuadren, el rebalanceo reparte sobre una base incompleta.',
                'home.act_targets_cta': 'Ajustar objetivos',
                'home.act_drift': '{name} se ha desviado del objetivo',
                'home.act_drift_body': 'Te {dir} {amount} € frente al objetivo. El próximo aporte puede corregirlo sin vender.',
                'home.act_drift_cta': 'Ver rebalanceo',
                'home.overweight': 'sobran',
                'home.underweight': 'faltan',
                'home.all_good': 'Cartera en rumbo',
                'home.all_good_body': 'Habría que mover {amount} €, dentro de banda. Rebalancear ahora sería coste sin beneficio.',
                'home.drift': 'A mover para cuadrar',
                'home.drift_hint': 'Cuánto sobra o falta en cada posición frente a tu objetivo.',
                'home.no_targets': 'Define pesos objetivo para ver la desviación.',
                'home.actual': 'Real',
                'home.target': 'Obj.',
                'home.see_positions': 'Ver todas las posiciones',
                'home.select_portfolio': 'Selecciona una cartera',
                'home.no_portfolio': 'Aún no tienes carteras',
                'home.no_portfolio_hint': 'Crea una para empezar a seguir tu patrimonio.',
                // --- Plan de aportación ---
                'plan.title': 'Plan de aportación',
                'banda.title_ok': "Todo dentro de banda",
                'banda.title_out': "{n} fuera de banda",
                'banda.explain': "Se reajusta cuando un fondo se desvía más de {banda} puntos porcentuales de su objetivo. Tu cartera está por {lado} de los {limite} €, que es donde cambia el umbral. Por debajo de esa banda, operar cuesta más de lo que corrige.",
                'banda.above': "encima",
                'banda.below': "debajo",
                'banda.vix': "Banda ensanchada por volatilidad alta",
                'banda.aggregate': "Banda a la mitad: acciones desviadas {pp} pp",
                'banda.min_op': "Operación mínima",
                'banda.min_op_hint': "Por debajo de este importe no se propone la compra y el dinero va al fondo que más lo necesita. Indexa usa 100 €. Si tu bróker ejecuta un plan automático sobre todos los fondos sin comisión, puedes bajarlo.",
                'plan.frequency': "Periodicidad",
                'plan.freq_monthly': "Mensual",
                'plan.freq_quarterly': "Trimestral",
                'plan.freq_biannual': "Semestral",
                'plan.target_date': "Fecha objetivo",
                'plan.target_hint': "Hasta cuándo piensas aportar. Se usa para los meses que verás por delante y para el horizonte de las simulaciones.",
                'plan.target_until': "Aportando hasta",
                'plan.months_left': "meses por delante",
                'plan.not_due': "Este mes no toca aportar.",
                'plan.saved_title': "Planes guardados",
                'plan.name_placeholder': "Nombre del plan",
                'plan.save_as': "Guardar",
                'plan.delete_saved': "Borrar plan guardado",
                'plan.hint': 'Fija cuánto aportas al mes. Cada mes se marca solo cuando registras el aporte en el rebalanceo.',
                'plan.monthly': 'Aporte mensual',
                'plan.growth': 'Subida anual',
                'plan.preview': 'Dentro de 5 años estarías aportando {y5} € al mes.',
                'plan.save': 'Guardar plan',
                'plan.cancel': 'Cancelar',
                'plan.edit': 'Editar plan',
                'plan.this_month': 'Toca este mes',
                'plan.done_month': 'Aporte del mes cumplido',
                'plan.of': 'de',
                'plan.months_met': 'meses cumplidos',
                'plan.contributed': 'aportado',
                // --- Análisis ---
                'an.no_data': 'Sin datos suficientes para este periodo.',
                'an.select_portfolio': 'Selecciona una cartera para analizarla.',
                'an.tab_perf': 'Retorno',
                'an.tab_risk': 'Riesgo',
                'an.tab_comp': 'Reparto',
                'an.tab_assets': 'Activos',
                'an.return': 'Rentabilidad',
                'an.cagr': 'CAGR',
                'an.cagr_sub': 'anualizada',
                'an.vs_bench': 'Frente al índice',
                'an.beta': 'Beta',
                'an.beta_sub': '1,00 = se mueve igual',
                'an.perf_note': 'Esta vista compara contra el S&P 500. Para TIR, TTWROR y más índices:',
                'an.perf_link': 'abrir Rentabilidad',
                'an.volatility': 'Volatilidad',
                'an.annualised': 'anualizada',
                'an.max_dd': 'Caída máxima',
                'an.max_dd_sub': 'peor racha del periodo',
                'an.per_unit': 'Retorno / riesgo',
                'an.per_unit_sub': 'CAGR ÷ volatilidad',
                'an.correlation': 'Correlación',
                'an.vs_bench_table': 'Tu cartera frente al índice',
                'an.metric': 'Métrica',
                'an.yours': 'Tuya',
                'an.top10': 'Top 10',
                'an.top10_sub': 'del patrimonio',
                'an.effective': 'Posiciones efectivas',
                'an.effective_sub': 'de {n} empresas',
                'an.top1': 'Mayor posición',
                'an.regions': 'Regiones',
                'an.overlap': 'Solapamiento entre fondos',
                'an.overlap_hint': 'Cuánta exposición repiten tus fondos entre sí. Solaparse mucho significa pagar dos comisiones por lo mismo.',
                'an.overlap_none': 'Necesitas al menos dos fondos para medir solapamiento.',
                'an.shared': 'valores en común',
                'an.overlap_warn': 'Prácticamente el mismo producto: plantéate consolidar en uno.',
                'an.xray_cta': 'Radiografía completa',
                'an.xray_cta_sub': 'Empresas, países, sectores y divisas',
                'an.open': 'Abrir',
                'an.best': 'Más aporta',
                'an.worst': 'Más resta',
                'an.on_portfolio': 'sobre la cartera',
                'an.assets': 'Todos los activos',
                'an.sort_impact': 'Impacto',
                'an.sort_change': 'Variación',
                'an.sort_weight': 'Peso',
                'hist.title': 'Rebalanceos aplicados',
                'hist.hint': 'De aquí salen los meses marcados en tu plan de aportación.',
                'hist.count': 'Rebalanceos',
                'hist.total': 'Total aportado',
                'hist.latest': 'Último',
                'hist.undo': 'Deshacer',
                'hist.delete': 'Eliminar',
                'hist.empty': 'Todavía no has aplicado ningún rebalanceo',
                'hist.empty_hint': 'Cuando apliques uno con aportación, aparecerá aquí y marcará el mes en tu plan.',
                // Dashboard allocation
                'dash.allocation': 'Asignación actual'
            },
            en: {
                // Sidebar
                'sidebar.rebalance': 'Rebalancer',
                'sidebar.performance': 'Performance',
                'sidebar.xray': 'X-Ray',
                'sidebar.analysis': 'Analysis',
                'sidebar.simulations': 'Simulations',
                'sidebar.news': 'News',
                'sidebar.settings': 'Settings',
                'header.xray': 'Portfolio X-Ray',
                // X-ray
                'xray.whole': 'Whole portfolio',
                'xray.companies': 'Companies (look-through)',
                'xray.countries': 'Countries',
                'xray.currencies': 'Currencies',
                'xray.sectors': 'Sectors',
                'xray.search': 'Find a company (e.g. NVIDIA, Toyota)…',
                'xray.no_data': 'Add assets to X-ray your portfolio.',
                'xray.holdings': 'Real holdings',
                'xray.top_country': 'Top country',
                'xray.top_sector': 'Top sector',
                'xray.exposure': 'Total exposure',
                'xray.direct': 'Direct',
                'xray.no_match': 'No company matches your search.',
                'xray.select_portfolio': 'Select a portfolio to X-ray it.',
                'sidebar.new_portfolio': 'New Portfolio',
                'sidebar.my_portfolios': 'My Portfolios',
                'sidebar.logout': 'Log Out',
                'portfolio.rename': 'Rename',
                'portfolio.duplicate': 'Duplicate',
                'portfolio.delete': 'Delete',
                'header.rebalancer': 'Rebalancer',
                'header.performance': 'Performance',
                'header.analysis': 'Asset Analysis',
                'header.simulations': 'Financial Projections',
                'header.news': 'Market News',
                'header.settings': 'Account Settings',
                'header.user': 'User',
                // News
                'news.sentiment': 'Global Portfolio Sentiment (RSI)',
                'news.score': 'Global Score',
                'news.analyzed': 'Analyzed News',
                'news.none': 'No recent news for your assets.',
                'news.rsi': 'RSI Indicator',
                'news.read': 'Read Article',
                'news.select_portfolio': 'Select a portfolio to see its news.',
                // Simulations
                'sim.select_portfolio': 'Portfolios to project',
                'sim.model': 'Model',
                'sim.params': '3. Parameters',
                'sim.horizon': 'Horizon',
                'sim.until': "until",
                'sim.snap_target': "Match my target date ({y} years)",
                'sim.years': 'Years',
                'sim.monthly': 'Monthly amount',
                'sim.growing': 'Growing Contribution (CPI)',
                'sim.annual_growth': 'Annual raise',
                'sim.apply_tax': 'Apply Tax (19%)',
                'sim.linear': 'Linear',
                'sim.linear_desc': 'Constant 7% annual return.',
                'sim.montecarlo': 'Monte Carlo',
                'sim.montecarlo_desc': 'Simulates real market volatility.',
                'sim.conservative': 'Cautious',
                'sim.conservative_desc': 'Low-return scenario: 4% a year.',
                'sim.empty': 'Configure and simulate',
                'sim.profit': 'Profit',
                'sim.loss': 'Loss',
                'sim.select_alert': 'Select at least one portfolio',
                'sim.error': 'Error running simulation.',
                'sim.source': 'Contributions',
                'sim.use_plan': 'My plan',
                'sim.custom': 'Custom',
                'sim.from_plan': 'Projected from your plan: {m} € a month, rising {g}% a year.',
                'sim.no_plan': 'No plan yet. Set one above or enter the values by hand.',
                // Contribution calendar
                'sched.title': 'Contribution calendar',
                'sched.constant_hint': 'You will put in the same amount every month of the horizon.',
                'sched.growing_hint': 'Your contribution rises',
                'sched.per_year': 'a year',
                'sched.per_month': 'a month',
                'sched.month': 'Month',
                'sched.year': 'Year',
                'sched.total': 'Total contributed',
                'sched.ends_at': 'You will end up contributing',
                'sched.empty': 'Enter a monthly contribution to see what you will put in each month.',
                // Dashboard / KPIs
                'kpi.total_value': 'Total Value',
                'kpi.current_capital': 'Current Capital',
                'kpi.risk': 'Risk Profile',
                'kpi.aggressive': 'Aggressive',
                'kpi.moderate': 'Moderate',
                'kpi.conservative': 'Conservative',
                'kpi.contribution': 'Monthly Contribution',
                'kpi.composition': 'Composition',
                'kpi.per_month': 'per month',
                'kpi.no_assets': 'No assets',
                'dash.search': 'Search (e.g. Apple, BTC)...',
                'dash.distribution': 'Distribution',
                'dash.plan_title': 'Rebalancing Plan',
                'dash.mode_contribute': 'Contribute only',
                'dash.mode_full': 'Full rebalance',
                'dash.mode_contribute_hint': 'Spread your monthly money, no selling.',
                'dash.mode_full_hint': 'Buy & sell to hit your targets exactly.',
                'dash.apply_contribute': 'Log Contribution',
                'dash.apply_full': 'Apply Rebalance',
                'dash.target_sum': 'Target sum',
                'dash.balanced': 'balanced',
                'dash.fix_settings': 'Set them in Settings',
                'dash.empty': 'Add assets to build your plan',
                'dash.history': 'Operations History',
                'dash.contribution_short': 'Contribution',
                'dash.to_invest_summary': 'To invest this month',
                'dash.unallocated': 'Unallocated',
                'dash.only_this': 'Contribute to this asset only',
                'dash.manual_amounts': 'Amounts set by hand',
                'dash.back_to_auto': 'Automatic split',
                // Table headers
                'th.asset': 'Asset',
                'th.price': 'Price',
                'th.units': 'Units',
                'th.value': 'Value',
                'th.now': 'Now',
                'th.target': 'Target',
                'th.invest': 'To invest',
                'th.totals': 'Totals',
                'act.buy': 'Buy',
                'act.sell': 'Sell',
                'act.hold': 'Hold',
                // Targets (Settings)
                'targets.title': 'Target Allocation',
                'targets.equal': 'Equal split',
                'targets.normalize': 'Scale to 100%',
                'targets.sum': 'Sum',
                'targets.balanced': 'Balanced (100%)',
                'targets.no_portfolio': 'Select or create a portfolio to set its targets.',
                'targets.no_assets': 'This portfolio has no assets yet. Add them from the Rebalancer.',
                'targets.hint': 'The sum should be 100%. You can also edit them in the Rebalancer table.',
                'targets.import': 'Import holdings (CSV)',
                // Performance
                'perf.title': 'Performance',
                'perf.since': 'Since',
                'perf.portfolio_value': 'Portfolio value',
                'perf.invested': 'Invested',
                'perf.cashflow': 'Cash flow',
                'perf.gain': 'Gain',
                'perf.tir': 'IRR (annual)',
                'perf.tir_hint': 'Internal rate of return, weighted by money and time.',
                'perf.simple_return': 'Total return',
                'perf.net_total': 'Net total',
                'perf.fees': 'Fees',
                'perf.taxes': 'Taxes',
                'perf.evolution': 'Value evolution',
                'perf.no_data': 'Import your Trade Republic CSV to see all portfolio stats.',
                'perf.net_hint': 'Enter fees and taxes to get your net total (optional).',
                'perf.select_portfolio': 'Select a portfolio to see its performance.',
                'perf.ttwror': 'TTWROR',
                'perf.ttwror_hint': 'Time-weighted rate of return.',
                'perf.price_gains_hint': 'Unrealised gains are measured since you bought, not from the start of the period: there is no historical price of your positions to scope them to the period.',
                'perf.price_gains': 'Price gains',
                'perf.realized': 'Realized (Gross)',
                'perf.dividends': 'Dividends (Gross)',
                'perf.interest': 'Interest (Gross)',
                'perf.total_gross': 'Total',
                'perf.cost_basis': 'Cost basis',
                'perf.period_since': 'Since',
                // Trade Republic CSV import
                'sync.title': "Sync with Trade Republic",
                'sync.stale_price': "Quotes corrected with your broker price",
                'sync.stale_price_hint': "The market price is far from the last one your broker executed, so the asset must be registered under a different ticker or currency. To keep your total right it is valued at the broker price. Shown as: app price → price used.",
                'pos.precio_csv': "broker price",
                'cargas.title': "Imported files",
                'cargas.hint': "What you uploaded each day and how it moved your invested total.",
                'cargas.empty': "You haven't imported any file yet",
                'cargas.empty_hint': "Upload the Trade Republic CSV from Positions and every import shows up here.",
                'cargas.operations': "operations",
                'cargas.total': "running total",
                'cargas.nothing_new': "nothing new",
                'cargas.delete': "Delete this file",
                'sync.new_ops': "new",
                'sync.already': "already stored",
                'reset.title': "Reset my data",
                'reset.hint': "Zeroes the account while keeping your portfolios and target weights.",
                'reset.cta': "Reset data",
                'reset.confirm_title': "This cannot be undone. It will delete:",
                'reset.item_history': "the rebalance history",
                'reset.item_units': "every asset's units (set to zero)",
                'reset.item_plans': "the contribution plan and saved plans",
                'reset.item_csv': "all imported CSVs",
                'reset.keeps': "Your portfolios, assets and target weights are kept.",
                'reset.confirm_cta': "Yes, reset",
                'reset.done': "Done: {h} rebalances deleted and {p} positions zeroed.",
                'reset.error': "Could not reset:",
                'aviso.title': "Time to update your portfolio",
                'aviso.pending_one': "This month's contribution has been executed:",
                'aviso.pending_many': "Missing contributions for",
                'aviso.later': "Not now",
                'movs.title': "Movements",
                'movs.hint': "Everything in the imported CSV.",
                'movs.movements': "movements",
                'movs.imported': "imported on",
                'movs.clear': "Delete stored CSV",
                'movs.empty': "You haven't imported a CSV yet",
                'movs.empty_hint': "Upload your Trade Republic export from Positions and your full history shows up here.",
                'movs.f_all': "All",
                'movs.f_contrib': "Contributions",
                'movs.f_income': "Income",
                'movs.plan': "plan",
                'movs.assets': "assets",
                'movs.more': "Show earlier months",
                'movs.buy': "Buy",
                'movs.sell': "Sell",
                'movs.dividend': "Dividend",
                'movs.interest': "Interest",
                'movs.card': "Card",
                'movs.transfer': "Transfer",
                'movs.other': "Other",
                'sync.hint': "Upload the transactions CSV and your units become the ones actually executed. The file never leaves your phone.",
                'sync.choose': "Choose CSV",
                'sync.transactions': "transactions",
                'sync.contributions': "contributions",
                'sync.new': "new",
                'sync.dca': "plan",
                'sync.assets': "assets",
                'sync.will_update': "These positions will be updated:",
                'sync.up_to_date': "Your positions already match the CSV. Nothing to apply.",
                'sync.unmatched': "Some assets could not be matched",
                'sync.only_app': "Only in the app",
                'sync.only_csv': "Only in the CSV",
                'sync.apply': "Update positions",
                'sync.save_only': "Save history",
                'sync.done': "Positions updated with real units.",
                'sync.err_apply': "Positions could not be updated.",
                'tr.err_empty': 'No transactions found in the file.',
                'tr.err_parse': 'Could not parse the CSV. Make sure it is the Trade Republic export.',
                'tr.since_first': 'Since your first purchase',
                'perf.go_import': "Go to Positions to import it",
                'tr.update': 'Update',
                'tr.imported_title': 'Data imported',
                'tr.imported_hint': 'Your Trade Republic history is loaded.',
                'tr.onboarding_title': 'Connect your Trade Republic history',
                'tr.onboarding_desc': 'Import your transaction CSV to see full detailed stats: returns, dividends, fees and more.',
                // Benchmark
                'bench.title': 'Benchmark comparison',
                'bench.hint': 'Your current holdings vs the major indices (base 100).',
                'bench.asset': 'Portfolio / Index',
                'bench.return': 'Return',
                'bench.cagr': 'CAGR annual.',
                'bench.vol': 'Volatility',
                'bench.maxdd': 'Max drawdown',
                'bench.your_portfolio': 'Your portfolio',
                'bench.no_data': 'Not enough data to compare.',
                'bench.select_hint': 'Pick one or more indices to compare.',
                // Benchmark — relative metrics (Beta / Correlation)
                'bench.rel_title': 'Against the market',
                'bench.rel_ref': 'Metrics calculated against',
                'bench.rel_change': 'Change reference index',
                'bench.rel_empty': 'Pick an index above to see your Beta and Correlation.',
                'bench.rel_insufficient': 'Not enough data',
                'bench.rel_not_computable': 'Not computable',
                'bench.rel_why_insufficient': 'Your portfolio and this index do not share enough history over this period.',
                'bench.rel_why_error': 'The index does not move at all over this period, so the relationship cannot be computed.',
                'bench.rel_points': 'sessions compared',
                'bench.beta_long': 'Beta',
                'bench.corr_long': 'Correlation',
                'bench.beta_amplify': 'Your portfolio amplifies the index moves.',
                'bench.beta_inline': 'Your portfolio moves almost in line with the index.',
                'bench.beta_damp': 'Your portfolio cushions the index moves.',
                'bench.beta_inverse': 'Inversely volatile: your portfolio moves against the index.',
                'bench.corr_strong': 'Very tight relationship with the index.',
                'bench.corr_moderate': 'Moderate relationship with the index.',
                'bench.corr_weak': 'Barely any relationship with the index.',
                'bench.corr_inverse': 'Inverse correlation: when the index rises, your portfolio tends to fall.',
                // Cost basis / profit since purchase
                'cost.title': 'Purchase history (cost)',
                'cost.hint': 'Paste your buys (symbol, date YYYY-MM-DD, units, price) or edit the average cost per asset. Your profit since purchase is computed. Stored on this device only.',
                'cost.placeholder': 'AAPL, 2025-11-24, 3, 180\nBTC-EUR, 2025-12-01, 0.05, 55000\n...',
                'cost.apply': 'Compute profit',
                'cost.profit_title': 'Profit since purchase',
                'cost.asset': 'Asset',
                'cost.avg_cost': 'Avg cost',
                'cost.invested': 'Invested',
                'cost.value': 'Current value',
                'cost.profit': 'Profit',
                'cost.since': 'Since',
                'cost.total': 'Total',
                'cost.none': 'No purchases defined yet. Paste your history above to see profit per asset.',
                'cost.total_profit': 'Total profit (since purchase)',
                // CSV import
                'csv.title': 'Sync holdings',
                'csv.hint': 'Paste a CSV (symbol/ISIN/name, units) from Trade Republic or Parqet to update your units. Since Fandance uses live market prices, when units match the value is identical to your broker.',
                'csv.placeholder': 'AAPL, 3.5\nVWCE, 12\n...',
                'csv.apply': 'Update units',
                'csv.matched': 'updated',
                'csv.unmatched': 'no match',
                // Analysis
                'analysis.title': 'Asset Analysis',
                'analysis.loading': 'Loading data...',
                'analysis.no_data': 'No data available.',
                'analysis.position_value': 'Your position value',
                // Settings
                'settings.appearance': 'Appearance',
                'settings.theme': 'Visual Theme',
                'settings.dark': 'Dark',
                'settings.light': 'Light',
                'settings.language': 'Language',
                'settings.account': 'Account',
                'settings.logout': 'Log Out',
                'settings.about': 'About',
                'settings.session': "Current session",
                'about.what': "Fandance spreads your monthly contribution across your index funds so the portfolio drifts back to your target weights on its own, without selling.",
                'about.q_rebalance': "How is the rebalance calculated?",
                'about.a_rebalance': "In \u00abContribute only\u00bb your monthly money goes to the assets furthest below their target, so you move back toward your plan without selling. \u00abFull rebalance\u00bb also sells to land exactly on target. This is the passive rebalancing approach used by robo-advisors like Indexa Capital.",
                'about.q_data': "Is my data safe?",
                'about.a_data': "Your portfolio lives in Supabase, and every request checks you own it before returning anything. The Trade Republic CSV is never uploaded: it is processed on your phone and wiped when you sign out.",
                'about.version': "Version",
                // Simulations
                'sim.title': 'Projections',
                'sim.calculate': 'Run Projection',
                'sim.investment': 'Total Invested',
                'sim.gross': 'Gross Value',
                'sim.net': 'Net after Tax',
                // Bottom Nav (mobile)
                'nav.rebalance': 'Portfolio',
                'nav.xray': 'X-Ray',
                'nav.analysis': 'Analysis',
                'nav.news': 'News',
                'nav.more': 'More',
                'nav.performance': 'Performance',
                'nav.simulations': 'Projections',
                'nav.settings': 'Settings',
                'nav.logout': 'Log Out',
                'nav.portfolio': 'Active portfolio',
                // X-Ray regions
                'xray.regions': 'Regions',
                'xray.geo_estimated': 'Funds do not publish a country breakdown: that part is estimated from the weights of the index they track',
                'xray.showing': 'Showing',
                'xray.of': 'of',
                'xray.load_more': 'Show more',
                'xray.show_all': 'Show all',
                'xray.collapse': 'Show less',
                'xray.unclassified': 'unclassified',
                'xray.coverage': 'Look-through coverage',
                'xray.coverage_note': 'Yahoo Finance only publishes the 10 largest holdings of each fund. The remaining weight is spread proportionally across them, so the company count is lower than the real one.',
                // --- Reorganised navigation ---
                'nav.home': 'Home',
                'nav.positions': 'Positions',
                'nav.xray_full': 'X-Ray',
                'nav.history': 'History',
                'header.home': 'Home',
                'header.positions': 'Positions',
                // --- Home ---
                'home.net_worth': 'Net worth',
                'home.since': 'Since',
                'home.value': 'Value',
                'home.no_history': 'No history yet',
                'home.act_targets': 'Your target weights do not add up to 100%',
                'home.act_targets_body': 'They currently add up to {sum}%. Until they balance, rebalancing splits over an incomplete base.',
                'home.act_targets_cta': 'Adjust targets',
                'home.act_drift': '{name} has drifted from target',
                'home.act_drift_body': 'You are {amount} € {dir} target. Your next contribution can fix it without selling.',
                'home.act_drift_cta': 'See rebalancing',
                'home.overweight': 'over by',
                'home.underweight': 'short by',
                'home.all_good': 'Portfolio on track',
                'home.all_good_body': 'You would move {amount} €, within band. Rebalancing now would be cost without benefit.',
                'home.drift': 'To move to rebalance',
                'home.drift_hint': 'How much each position is over or short of your target.',
                'home.no_targets': 'Set target weights to see drift.',
                'home.actual': 'Actual',
                'home.target': 'Target',
                'home.see_positions': 'See all positions',
                'home.select_portfolio': 'Select a portfolio',
                'home.no_portfolio': 'No portfolios yet',
                'home.no_portfolio_hint': 'Create one to start tracking your net worth.',
                // --- Contribution plan ---
                'plan.title': 'Contribution plan',
                'banda.title_ok': "All within band",
                'banda.title_out': "{n} outside the band",
                'banda.explain': "A rebalance happens when a fund drifts more than {banda} percentage points from its target. Your portfolio is {lado} the {limite} € mark, where the threshold changes. Below that band, trading costs more than it corrects.",
                'banda.above': "above",
                'banda.below': "below",
                'banda.vix': "Band widened by high volatility",
                'banda.aggregate': "Band halved: equities off by {pp} pp",
                'banda.min_op': "Minimum operation",
                'banda.min_op_hint': "Below this amount the purchase is not proposed and the money goes to the fund that needs it most. Indexa uses 100 €. If your broker runs an automated plan across all funds with no commission, you can lower it.",
                'plan.frequency': "Frequency",
                'plan.freq_monthly': "Monthly",
                'plan.freq_quarterly': "Quarterly",
                'plan.freq_biannual': "Every 6 months",
                'plan.target_date': "Target date",
                'plan.target_hint': "How long you plan to keep contributing. Drives the months shown ahead and the default simulation horizon.",
                'plan.target_until': "Contributing until",
                'plan.months_left': "months to go",
                'plan.not_due': "No contribution due this month.",
                'plan.saved_title': "Saved plans",
                'plan.name_placeholder': "Plan name",
                'plan.save_as': "Save",
                'plan.delete_saved': "Delete saved plan",
                'plan.hint': 'Set how much you contribute monthly. Each month ticks itself once you log the contribution in a rebalance.',
                'plan.monthly': 'Monthly amount',
                'plan.growth': 'Annual raise',
                'plan.preview': 'In 5 years you would be contributing {y5} € a month.',
                'plan.save': 'Save plan',
                'plan.cancel': 'Cancel',
                'plan.edit': 'Edit plan',
                'plan.this_month': 'Due this month',
                'plan.done_month': 'This month is covered',
                'plan.of': 'of',
                'plan.months_met': 'months met',
                'plan.contributed': 'contributed',
                // --- Analysis ---
                'an.no_data': 'Not enough data for this period.',
                'an.select_portfolio': 'Select a portfolio to analyse it.',
                'an.tab_perf': 'Return',
                'an.tab_risk': 'Risk',
                'an.tab_comp': 'Mix',
                'an.tab_assets': 'Assets',
                'an.return': 'Return',
                'an.cagr': 'CAGR',
                'an.cagr_sub': 'annualised',
                'an.vs_bench': 'Vs benchmark',
                'an.beta': 'Beta',
                'an.beta_sub': '1.00 = moves alike',
                'an.perf_note': 'This view compares against the S&P 500. For IRR, TTWROR and more indices:',
                'an.perf_link': 'open Performance',
                'an.volatility': 'Volatility',
                'an.annualised': 'annualised',
                'an.max_dd': 'Max drawdown',
                'an.max_dd_sub': 'worst run in period',
                'an.per_unit': 'Return / risk',
                'an.per_unit_sub': 'CAGR ÷ volatility',
                'an.correlation': 'Correlation',
                'an.vs_bench_table': 'Your portfolio vs the index',
                'an.metric': 'Metric',
                'an.yours': 'Yours',
                'an.top10': 'Top 10',
                'an.top10_sub': 'of net worth',
                'an.effective': 'Effective holdings',
                'an.effective_sub': 'out of {n} companies',
                'an.top1': 'Largest holding',
                'an.regions': 'Regions',
                'an.overlap': 'Fund overlap',
                'an.overlap_hint': 'How much exposure your funds repeat. Heavy overlap means paying two fees for the same thing.',
                'an.overlap_none': 'You need at least two funds to measure overlap.',
                'an.shared': 'shared holdings',
                'an.overlap_warn': 'Practically the same product: consider consolidating into one.',
                'an.xray_cta': 'Full X-Ray',
                'an.xray_cta_sub': 'Companies, countries, sectors and currencies',
                'an.open': 'Open',
                'an.best': 'Biggest contributor',
                'an.worst': 'Biggest drag',
                'an.on_portfolio': 'on portfolio',
                'an.assets': 'All assets',
                'an.sort_impact': 'Impact',
                'an.sort_change': 'Change',
                'an.sort_weight': 'Weight',
                'hist.title': 'Applied rebalances',
                'hist.hint': 'This is what ticks the months in your contribution plan.',
                'hist.count': 'Rebalances',
                'hist.total': 'Total contributed',
                'hist.latest': 'Latest',
                'hist.undo': 'Undo',
                'hist.delete': 'Delete',
                'hist.empty': 'You have not applied any rebalance yet',
                'hist.empty_hint': 'Once you apply one with a contribution, it shows up here and ticks the month in your plan.',
                // Dashboard allocation
                'dash.allocation': 'Current allocation'
            }
        };
        return translations[language][key] || key;
    };

    return (
        <GlobalContext.Provider value={{ theme, setTheme, language, setLanguage, t }}>
            {children}
        </GlobalContext.Provider>
    );
};
